spring:
    application:
        name: cacms
    datasource:
        url: jdbc:h2:file:/tmp/digital-sky-h2-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
            path: '/h2'
            settings:
              web-allow-others: true


server:
  port: 9443
  http-port: 9000
  ssl:
    enabled: true
    key-alias: tomcat-localhost
    key-password: cacms789
    key-store: classpath:keystore.jks
    key-store-provider: SUN
    key-store-type: JKS
    key-store-password: cacms789

